const basePath = import.meta.env.MODE === 'production'
    ? import.meta.env.VITE_PUBLIC_PATH
    : ''

const moreproductyitems = [
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        cookingOptions: ['boiling', 'frying'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: false,
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1999,
        oldPrice: 2400,
        cookingOptions: ['alive'],
        labels: ['promo'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        cookingOptions: ['boiling', 'alive'],
        labels: ['hit'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['alive', 'boiling', 'frying'],
        labels: ['hit', 'promo'],
        href: `${basePath}/kalmar`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'alive', 'frying'],
        labels: ['hit', 'promo'],
        href: `${basePath}/kalmar`,
    },
];

export default moreproductyitems;