const basePath = import.meta.env.MODE === 'production'
    ? import.meta.env.VITE_PUBLIC_PATH
    : ''

const moreproductyitems = [
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар командорский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo', 'new'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар первый',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        cookingOptions: ['boiling', 'frying'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар второй',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Царский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: false,
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Грибной',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1999,
        oldPrice: 2400,
        cookingOptions: ['alive'],
        labels: ['promo', 'new'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Сациви',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Рататуй',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Корейский',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Бризоль',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: false,
        price: 1500,
        cookingOptions: ['boiling', 'alive'],
        labels: ['hit'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Оригиналь',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Сметанный',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['frying', 'boiling', 'alive'],
        labels: ['hit', 'promo'],
        href: `${basePath}/product-page`,
    },
    {
        image: '/src/assets/images/product/product.jpg',
        title: 'Кальмар Томатный',
        description: 'Метод сухой заморозки продукции, что позволяет сохранить вкус и полезные свойства.',
        inStock: true,
        price: 1500,
        oldPrice: 1800,
        cookingOptions: ['boiling', 'frying', 'alive'],
        labels: ['hit', 'promo', 'new'],
        href: `${basePath}/product-page`,
    },
];

export default moreproductyitems;